from lightcontrol import *


#on()
#set_brightness(100)
#set_brightness_and_off()
#set_brightness_and_on()
#set_warmth()
#set_white()
#get_brightness()
#change_bulb_name()
#cool()
#up()\
#down()
#get_colour()
#get_real_brightness()
#get_real_warmth()
#get_warmth()
#is_on()
#max()
on_off()
#reconnect()
#set_colour()
#set_real_brightness()
#set_real_brightness_and_on()
#set_real_warmth()
#warm()
#bulb_ip()